config/routes.rb
Gsapi2::Application.routes.draw do
  get "page/parse"

  post "houses/notes" => "houses#update_notes"
  post "houses/contact" => "houses#update_contact"
  post "houses/address" => "houses#update_address"
  resources :houses

  resources :rates

  resources :reviews

  resources :factors

  devise_for :users, :controllers => { :registrations => "registrations" , sessions: "sessions" } , :token_authentication_key => 'authentication_key'

  get '/login' => 'user#login' , :as => 'user_root'
  get '/signup' => 'user#signup'

  

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)
    # respond_to do |format|
    @house.user_id = current_user.id
    puts current_user.inspect
      if @house.save
        render json: {:success => true}
        # render action: 'show', status: :created, location: @house
        # format.html { redirect_to @house, notice: 'House was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @house }
      else
        render json: @house.errors, status: :unprocessable_entity 
        # format.html { render action: 'new' }
        # format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update_address
    # respond_to do |format|
    @house = House.find_by(house_id: params[:house][:house_id],user_id: current_user.id)
    puts "*"*100
    puts @house.inspect
    puts "*"*100
      if @house.update(house_params)
        render json: {success: true}
        # format.html { redirect_to @house, notice: 'House was successfully updated.' }
        # format.json { head :no_content }
      else
        render json: @house.errors, status: :unprocessable_entity 
        # format.html { render action: 'edit' }
        # format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    # end
  end

  #----------------------------Make the notes--------------------------------#
  def update_notes
    # respond_to do |format|
    @house = House.find_by house_id: params[:house][:house_id], user_id: current_user.id
    puts @house.Notes
    @house.Notes = params[:house][:Notes]
      # @house = House.where("house_id = ? and user_id = ?",params[:house_id])
      if @house.save
        # format.html { redirect_to @house, notice: 'House was successfully updated.' }
        # format.json { head :no_content }
        render json: {success: true}
      else
        render json: @house.errors, status: :unprocessable_entity 
        # format.html { render action: 'edit' }
        # format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    # end
  end

  def update_contact
    # respond_to do |format|
    @house = House.find_by house_id: params[:house][:house_id], user_id: current_user.id
    # puts @house.inspect
    # puts "*"*100
    # puts params[:house][:phone]
    # puts @house.contact
    @house.contact = params[:house][:phone]
    @house.email = params[:house][:email]
      # @house = House.where("house_id = ? and user_id = ?",params[:house_id])
      if @house.save
        # format.html { redirect_to @house, notice: 'House was successfully updated.' }
        # format.json { head :no_content }
        render json: {success: true}
      else
        render json: @house.errors, status: :unprocessable_entity 
        # format.html { render action: 'edit' }
        # format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    # end
  end


  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:country, :state, :city, :addl1, :addl2, :unit, :zip , :label , :street ,:Notes , :house_id, :phone, :email)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :addl1 %><br>
    <%= f.text_area :addl1 %>
  </div>
  <div class="field">
    <%= f.label :addl2 %><br>
    <%= f.text_area :addl2 %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<h1>Listing houses</h1>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>State</th>
      <th>City</th>
      <th>Addl1</th>
      <th>Addl2</th>
      <th>Unit</th>
      <th>Zip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.country %></td>
        <td><%= house.state %></td>
        <td><%= house.city %></td>
        <td><%= house.addl1 %></td>
        <td><%= house.addl2 %></td>
        <td><%= house.unit %></td>
        <td><%= house.zip %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @house.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @house.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @house.city %>
</p>

<p>
  <strong>Addl1:</strong>
  <%= @house.addl1 %>
</p>

<p>
  <strong>Addl2:</strong>
  <%= @house.addl2 %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @house.unit %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @house.zip %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>