config/routes.rb
Gsapi2::Application.routes.draw do
  get "page/parse"

  post "houses/notes" => "houses#update_notes"
  post "houses/contact" => "houses#update_contact"
  post "houses/address" => "houses#update_address"
  resources :houses

  resources :rates

  resources :reviews

  resources :factors

  devise_for :users, :controllers => { :registrations => "registrations" , sessions: "sessions" } , :token_authentication_key => 'authentication_key'

  get '/login' => 'user#login' , :as => 'user_root'
  get '/signup' => 'user#signup'

  

end

app/models/factor.rb
class Factor < ActiveRecord::Base

	has_many :reviews
	belongs_to :houses

end

app/controllers/factors_controller.rb
class FactorsController < ApplicationController
  before_filter :authenticate_user! , only: [:create]
  before_action :set_factor, only: [:show, :edit, :update, :destroy]

  # GET /factors
  # GET /factors.json
  def index
    @factors = Factor.all
  end

  # GET /factors/1
  # GET /factors/1.json
  def show
  end

  # GET /factors/new
  def new
    @factor = Factor.new
  end

  # GET /factors/1/edit
  def edit
  end

  # POST /factors
  # POST /factors.json
  def create
    @factor = Factor.new(factor_params)
    respond_to do |format|
      if @factor.save
        # format.html { redirect_to @factor, notice: 'Factor was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @factor }
        render action: 'show', status: :created, location: @factor
      else
        # format.html { render action: 'new' }
        # format.json { render json: @factor.errors, status: :unprocessable_entity }
        render json: @factor.errors, status: :unprocessable_entity
      end
    end
  end

  # PATCH/PUT /factors/1
  # PATCH/PUT /factors/1.json
  def update
    respond_to do |format|
      if @factor.update(factor_params)
        format.html { redirect_to @factor, notice: 'Factor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @factor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factors/1
  # DELETE /factors/1.json
  def destroy
    @factor.destroy
    respond_to do |format|
      format.html { redirect_to factors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factor
      @factor = Factor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factor_params
      params.require(:factor).permit(:name, :description)
    end
end

app/helpers/factors_helper.rb
module FactorsHelper
end

app/views/factors/_form.html.erb
<%= form_for(@factor) do |f| %>
  <% if @factor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factor.errors.count, "error") %> prohibited this factor from being saved:</h2>

      <ul>
      <% @factor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factors/edit.html.erb
<h1>Editing factor</h1>

<%= render 'form' %>

<%= link_to 'Show', @factor %> |
<%= link_to 'Back', factors_path %>

app/views/factors/index.html.erb
<h1>Listing factors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @factors.each do |factor| %>
      <tr>
        <td><%= factor.name %></td>
        <td><%= factor.description %></td>
        <td><%= link_to 'Show', factor %></td>
        <td><%= link_to 'Edit', edit_factor_path(factor) %></td>
        <td><%= link_to 'Destroy', factor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Factor', new_factor_path %>

app/views/factors/new.html.erb
<h1>New factor</h1>

<%= render 'form' %>

<%= link_to 'Back', factors_path %>

app/views/factors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @factor.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @factor.description %>
</p>

<%= link_to 'Edit', edit_factor_path(@factor) %> |
<%= link_to 'Back', factors_path %>