config/routes.rb
Gsapi2::Application.routes.draw do
  get "page/parse"

  post "houses/notes" => "houses#update_notes"
  post "houses/contact" => "houses#update_contact"
  post "houses/address" => "houses#update_address"
  resources :houses

  resources :rates

  resources :reviews

  resources :factors

  devise_for :users, :controllers => { :registrations => "registrations" , sessions: "sessions" } , :token_authentication_key => 'authentication_key'

  get '/login' => 'user#login' , :as => 'user_root'
  get '/signup' => 'user#signup'

  

end

app/models/rate.rb
class Rate < ActiveRecord::Base

	belongs_to :review

end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)
    @rate.user_id = current_user.id
    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rate }
      else
        format.html { render action: 'new' }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:text_input, :integer_input, :start_range, :end_range, :float_input , :review_id)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% @rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text_input %><br>
    <%= f.text_area :text_input %>
  </div>
  <div class="field">
    <%= f.label :integer_input %><br>
    <%= f.number_field :integer_input %>
  </div>
  <div class="field">
    <%= f.label :start_range %><br>
    <%= f.number_field :start_range %>
  </div>
  <div class="field">
    <%= f.label :end_range %><br>
    <%= f.number_field :end_range %>
  </div>
  <div class="field">
    <%= f.label :float_input %><br>
    <%= f.text_field :float_input %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<h1>Listing rates</h1>

<table>
  <thead>
    <tr>
      <th>Text input</th>
      <th>Integer input</th>
      <th>Start range</th>
      <th>End range</th>
      <th>Float input</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rates.each do |rate| %>
      <tr>
        <td><%= rate.text_input %></td>
        <td><%= rate.integer_input %></td>
        <td><%= rate.start_range %></td>
        <td><%= rate.end_range %></td>
        <td><%= rate.float_input %></td>
        <td><%= link_to 'Show', rate %></td>
        <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
        <td><%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New rate</h1>

<%= render 'form' %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text input:</strong>
  <%= @rate.text_input %>
</p>

<p>
  <strong>Integer input:</strong>
  <%= @rate.integer_input %>
</p>

<p>
  <strong>Start range:</strong>
  <%= @rate.start_range %>
</p>

<p>
  <strong>End range:</strong>
  <%= @rate.end_range %>
</p>

<p>
  <strong>Float input:</strong>
  <%= @rate.float_input %>
</p>

<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>